### ISSUE TITLE
Will this support Zotero sync?

### ISSUE THREAD

**Issue by ripefig** [andyljones/zonotable#1]
Just wondering

**Comment by andyljones** [comment]
Nope. The only thing in here right now is the Zotero translation server, which is a small part of the full Zotero client. I think Zotero sync has got a web API though, so writing a script to take Zotero cloud items -> markdown notes on your harddrive should be pretty easy. He says, never having used Zotero's web API.

If you do decide to do that,  you'll want to try and get an 'api JSON' formatted object out of the web API, then run it through [something like this](https://github.com/andyljones/zonotable/blob/master/src/notableEndpoint.js#L17-L29). There's an example of api JSON format [in the tests](https://github.com/andyljones/zonotable/blob/master/test/markdown_test.js#L13-L112).

**Comment by ripefig** [comment]
I can't be of much help I am afraid. But I wouldn't waste time on the Zotero Web API. I think bibtex is a better route. Zotero can output to bibtex continuously or on demand (See Zotxt and BetterBibtex projects.)

**Comment by andyljones** [comment]
FWIW, @kcajf has now put together a [Notable-Zotero sync](https://github.com/kcajf/notable-zotero-importer) that might suit.
