### ISSUE TITLE
Will this support inline citations?

### ISSUE THREAD

**Issue by ripefig** [andyljones/zonotable#2]
This is the main thing virtually all note apps are missing. Good support for citations with plenty of feedback about which citation key refers to what.

I think adding an inline bibtex/yaml/json fallback would be optimal, to maintain note legibility in the absence of a database.

**Comment by andyljones** [comment]
It can do _something_ like that at the moment. Each paper is saved to a file called `paper-$TITLE-$HASH_OF_URL.md`. For example, [this paper](https://arxiv.org/abs/1803.02811) is saved down as 
```
papers-Accelerated Methods for Deep Reinforcement Learning-6206f5a1.md
```
The filename is listed at the end of the metadata, and then you can create a link in another note with Notable's `[link text](@note/filename)` syntax.
